name: Deploy VitePress site to Pages

on:
  push:
    branches: [main] # 当 main 分支有 push 时触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build with VitePress
        run: npm run build # 编译 Markdown 为 HTML
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # 上传编译后的静态文件
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
